import { JetBrains_Mono } from "next/font/google";
// import "./globals.css";
import Header from "@/components/Header";
import "./globals.css";
import { Metadata } from "next";
// import StairTransition from "@/components/StairTransition";

export const metadata: Metadata = {
  title: "Exotic Car",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico", // Update with the actual path
    apple: "./favicon.ico", // Optional for Apple touch icon
  },
};

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable}`}>
        {/* <Header /> */}
        {/* <StairTransition /> */}
        {children}
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        
//         {children}
//       </body>
//     </html>
//   );
// }
